# Override env variables (specified in env.yaml) for development environment.
env_variables:
    ALLOWED_HOSTS: "localhost, 127.0.0.1, 0.0.0.0, django, modularhistory.dev.net"
    BASE_URL: http://modularhistory.dev.net
    DEBUG: True
    DJANGO_LOG_LEVEL: INFO
    DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
    DJANGO_SUPERUSER_PASSWORD: admin
    DUMMY_CACHE: True
    ENVIRONMENT: dev
    HTTPS: off
    MYPY_CACHE_DIR: .cache/mypy
    POSTGRES_DB: modularhistory
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    SEND_SENTRY_EVENTS: False
    SHA: latest
    USE_CELERY: False
    USE_PARALLEL_INDEX_BUILDING: 0
